parameters:
#    overblog_rest_client.example.class: Overblog\RestClientBundle\Example

services:
#    overblog_rest_client.example:
#        class: %overblog_rest_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
