parameters:
  ws_client.class: Overblog\WsClientBundle\Client\WsClient
  urls: %ws_client.urls%

services:
  ws_client:
    class: %ws_client.class%
    arguments: [%urls%, @ws_client.logger]

  ws_client.logger:
    class: Overblog\WsClientBundle\Logging\WsClientLogger

  data_collector.ws_client:
    class: Overblog\WsClientBundle\DataCollector\WsClientDataCollector
    arguments: [@ws_client.logger]
    tags:
        - { name: data_collector, template: "OverblogWsClientBundle:Collector:ws", id: "ws_client" }